### PR TITLE
Fix board config dropdowns

### PR DESCRIPTION
**Pull request by alexyaoyang**
https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/8

### CODE REVIEW

**Comment by alexyaoyang** [comment]
https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/9

**Comment by alexyaoyang** [comment]
https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/10

**Comment by spiliot** [comment]
Code is good, but this pull request is missing a description so what was broken before and got fixed now?

**Comment by alexyaoyang** [comment]
Thanks for pointing out! Will fix it in the following commit :smiley:

**Changes**
- Changed to populate dropdowns with GET instead of utilizing compilerflasher.js as programmer options are needed in the populated dropdown.
- Added the comm port drop down in iframe so users can choose which port their microprocessor is attached to.
- Fix codestyle inconsistencies in codes

https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/11

**Comment by tzikis** [comment]
@alexyaoyang hey man, you'll have to pull the latest changes to the master branch and merge again because I added Coveralls. Sorry for the inconvenience :/

**Comment by alexyaoyang** [comment]
Sure thing! No problem! :)

**Comment by alexyaoyang** [comment]
@spiliot Sorry, I accidentally merged this PR, I thought it's merging the previous PR and this PR in one single PR. I've created a revert PR, but please fix it as needed! Thanks!

**Pull request merged**
