### PR TITLE
Landing page initial commit

### PR DESCRIPTION
**Pull request by alexyaoyang**
### Changes
- Renamed flash page to a more suitable name so we don't confuse the landing page with it.
- Added landing page html css, had none previously.
- Added landing page assets, had none previously.
- Updated favicon to Neuralyzer's. Previously was using Symfony's favicon.
- Added unit tests for landing pag, had none previously.

Ready for review, @spiliot, thanks!

https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/30
https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/32

### CODE REVIEW

**Comment by spiliot** [comment]
Do we have permission to use the microprocessor image added in https://github.com/codebendercc/Neuralyzer/pull/24/commits/f2beaafdab59652b89b4c51257daed46380350cc? Where is it pulled from?

**Comment by alexyaoyang** [comment]
@spiliot Have changed to a royalty free photo :)

**Comment by spiliot** [comment]
Ok great. If you're adding commits after the review you should remember to change the flag back to `readyForReview` though ;)

**Comment by alexyaoyang** [comment]
Oops, my bad, changed it!

**Pull request merged**
