### PR TITLE
Firmware database

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Changes
- Created the firmware database.

@spiliot Only two new commits here - 110965e & f1ea4f8. Thanks!

### CODE REVIEW

**Comment by spiliot** [comment]
@alexyaoyang This one has a merge conflict now, can you have a look?

**Comment by alexyaoyang** [comment]
Hi @spiliot, I followed the merge instructions and the changes are merged into firmware-database branch now. Nothing reflects here though.

**Comment by spiliot** [comment]
@alexyaoyang What you seem to have done is make a PR from _your_ fork of the project and then push the changes to a branch of _this_ project, which doesn't have a standing pull request so changes can't be seen.

Github's instructions assume that since you have write privileges to this project you would make changes originating from _this_ project and not _yours_. So you need to either merge `codebendercc/neuralyzer/master` to your `alexyaoyang/neuralizer/firmware-database`  branch and push again (which will hopefully update this PR) or fix this in this project and make a new PR.

Since I don't have access to _your_ project, I'll go ahead and fix the conflict here, making a new PR the points to this one.

**Comment by alexyaoyang** [comment]
Got it, that explains, thanks @spiliot!

**Pull request closed without merging**
