### PR TITLE
Refactor all front-end code

### PR DESCRIPTION
**Pull request by alexyaoyang**
This PR is chained with landing page PR #24, since we are refactoring front-end code.
## Changes
- Moved nav, footer, common CSS and JS to base.html.twig
- Removed all comments
- Removed unnecessary/repeated code
- Refactor all codestyle
- Edited html code to use Twig template blocks

Ready for review, thanks!

https://insight.sensiolabs.com/projects/a371effa-c11d-473f-844d-d5f421df79be/analyses/44

### CODE REVIEW

**Comment by tzikis** [comment]
Hey Alex, just a small comment. It feels like you’ve been refraining from going into the DB stuff, probably because of some small (healthy) fear of the unknown. Which is what we’ll have to improve during FOA, so let’s prioritize this ;) Besides, it will take you some time to get up to speed

After all, the goal is to have some functional prototype. Even if some things don’t work, we should have all basic pages work and communicate to the database, insert stuff, etc. In fact, it’s better to have the basic structure of the DB defined than good-looking pages. Anyone can pick something up if the “skeleton” is there and they only have to work on specific parts (i.e. improving the UI)

**Comment by alexyaoyang** [comment]
Hey Vasilis,

Noted! I will focus more on back end stuffs now. Thanks for the feedback!

**Comment by alexyaoyang** [comment]
Hi Vasilis,

Just confirming that you’ve received my previous reply?

I’ve sent it out but I don’t see it in my sent folders. My hotmail seems to be having some problem.

I will focus more on DB & backend portions. I was previously waiting for the PR to be merged because new DB PRs will have to be chained on previous PRs, but I will now proceed to chain them.

Have a great week!

Thanks,
-- 
Alex Yao

On March 4, 2016 at 1:35:53 AM, Vasilis Georgitzikis (notifications@github.com) wrote:

Hey Alex, just a small comment. It feels like you’ve been refraining from going into the DB stuff, probably because of some small (healthy) fear of the unknown. Which is what we’ll have to improve during FOA, so let’s prioritize this ;) Besides, it will take you some time to get up to speed

After all, the goal is to have some functional prototype. Even if some things don’t work, we should have all basic pages work and communicate to the database, insert stuff, etc. In fact, it’s better to have the basic structure of the DB defined than good-looking pages. Anyone can pick something up if the “skeleton” is there and they only have to work on specific parts (i.e. improving the UI)

Vasilis

**Comment by tzikis** [comment]
hey Alex,
yeap, i got it, all good

**Pull request merged**
